### ISSUE TITLE
#TK55 - Implementar accesibilidad como en EditarSocio.xml y Registro.xml en todas las pantallas (mencionadas en descripción de la issue).

### ISSUE THREAD

**Issue by horacioequiroga** [grupoA7ISPC/MisRutinas-PracticasProfesionalizante#65]
- [x] **REGISTRO:** @PaylemanC 

- [x] **EDICIÓN DE SOCIO:** @estebanmartins 
- [x] **EDICIÓN DE ENTRENADOR:** @fede9087 
- [x] **CREACIÓN DE SOCIO:**  @verofx 
- [x] **CREACIÓN DE ENTRENADOR:** @fede9087 
- [x] **VISTA DE SOCIO:** @verofx 
- [x] **VISTA DE ENTRENADOR:** @fede9087 
- [x] **CREACIÓN DE CLASES:** @horacioequiroga 
- [x] **EDICIÓN DE CLASES:** @estebanmartins 
- [x] **VISTA DE CLASES:** @horacioequiroga 
- [x] **INICIO DE SESIÓN:** @PaylemanC 

Por cada página especialmente:

- Botón de volver hacia atrás.
- Buen contrast ratio entre background/color de letras.
- Inputs con labels.
- Si es posible: mensajes de error con @color/danger bajo inputs (ej. Registro).

**Comment by PaylemanC** [comment]
REGISTRO y LOGIN implementados.

**Comment by fede9087** [comment]
Entrenador implementado.

**Comment by estebanmartins** [comment]
Ver clases y edicion clases implementados
